apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo2
  namespace: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: nginx:latest
          ports:
            - containerPort: 80

