apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-first-app-gitops 
  namespace: argocd        
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: argo-test
    notifications.argoproj.io/subscribe.email: youna2510@naver.com
    notifications.argoproj.io/subscribe.on-health-degraded.slack: argo-test
    notifications.argoproj.io/subscribe.on-sync-failed.email: youna2510@naver.com
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argo-test
    notifications.argoproj.io/subscribe.on-health-degraded.email: youna2510@naver.com
spec:
  project: default 
  source:
    repoURL: https://github.com/youna2510/toy-argoCD.git
    targetRevision: HEAD
    path: apps   
  destination:
    server: https://kubernetes.default.svc 
    namespace: default 
  syncPolicy:
    automated:   
      prune: true
      selfHeal: true
